AWSTemplateFormatVersion: 2010-09-09
Description: Basic infrastructure for AWS Config demonstration

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: demo-aws-config-test-rules
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
